"""FastAPI application entry point.

Lifespan
--------
1. Run ``alembic upgrade head`` via subprocess so migrations are always applied
   before the first request is served — even in a fresh container.
2. Create the asyncpg pool and attach it to ``app.state``.
3. Initialise a fresh JobState singleton on ``app.state``.
4. On shutdown: close the pool gracefully.

Routing
-------
* /job/*      — job control (start, status, stop)
* /places/*   — place management (upload, list, detail)
* /           — serves static/index.html
* /static/*   — static assets
* /docs       — Swagger UI (auto-generated by FastAPI)
"""

import logging
import os
import subprocess
import sys
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pythonjsonlogger import jsonlogger

from app.database import close_pool, create_pool
from app.routers import job, places
from app.worker import JobState

# ---------------------------------------------------------------------------
# Structured JSON logging (compatible with log aggregators like Datadog / ELK)
# ---------------------------------------------------------------------------

handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(
    jsonlogger.JsonFormatter(
        fmt="%(asctime)s %(levelname)s %(name)s %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
    )
)
logging.basicConfig(level=logging.INFO, handlers=[handler])

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------


def _run_alembic_with_retry(max_attempts: int = 10, base_delay: float = 2.0) -> None:
    """Run ``alembic upgrade head``, retrying on transient DNS / connection errors.

    Docker Compose's ``depends_on: condition: service_healthy`` guarantees that
    PostgreSQL is accepting connections, but the container's DNS resolver can
    take a couple of seconds to resolve the ``db`` service name after the
    container first starts.  This function retries with linear back-off so the
    app waits out that window without crashing.

    Raises RuntimeError on the final attempt if alembic still fails.
    """
    # Pass DATABASE_URL explicitly so the subprocess always has the right value
    # even if the environment is somehow partially inherited.
    env = {**os.environ}

    for attempt in range(1, max_attempts + 1):
        logger.info("running alembic upgrade head (attempt %d/%d)", attempt, max_attempts)
        result = subprocess.run(
            ["alembic", "upgrade", "head"],
            capture_output=True,
            text=True,
            env=env,
        )
        if result.returncode == 0:
            logger.info("alembic: %s", result.stdout.strip() or "no new migrations")
            return

        stderr = result.stderr.strip()
        logger.warning("alembic attempt %d/%d failed: %s", attempt, max_attempts, stderr)

        # Stop retrying on errors that won't improve with time (bad SQL, etc.)
        transient_keywords = ("name resolution", "could not connect", "connection refused",
                              "could not translate", "temporarily unavailable")
        is_transient = any(kw in stderr.lower() for kw in transient_keywords)

        if attempt < max_attempts and is_transient:
            time.sleep(base_delay)
            continue

        # Non-transient error or out of retries — fail fast
        raise RuntimeError(f"Alembic migration failed (attempt {attempt}/{max_attempts}):\n{stderr}")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup / shutdown hook.

    Runs Alembic migrations synchronously before anything else so the schema
    is always current when the first request arrives.  Using subprocess keeps
    the migration path identical to running ``alembic upgrade head`` manually,
    and avoids the complexity of a synchronous SQLAlchemy engine inside an
    async app.
    """
    # Run alembic with retries.
    # Despite depends_on:service_healthy, Docker's embedded DNS (127.0.0.11)
    # can briefly fail to resolve the "db" service name in the first seconds
    # after the container starts — manifesting as "Temporary failure in name
    # resolution".  Retrying with back-off reliably bridges that window.
    _run_alembic_with_retry()

    # Create the asyncpg pool and store it for dependency injection
    pool = await create_pool()
    app.state.pool = pool

    # Singleton job state shared between the worker and job control endpoints
    app.state.job_state = JobState()

    logger.info("startup complete")
    yield

    # Graceful shutdown: wait for in-flight queries
    logger.info("shutting down — closing DB pool")
    await close_pool()


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Places Photo Worker",
    description="Fetches Google Places photo metadata and stores it as JSONB.",
    version="0.1.0",
    lifespan=lifespan,
)

# Register routers
app.include_router(job.router)
app.include_router(places.router)

# Serve static assets (CSS, JS, images if any)
app.mount("/static", StaticFiles(directory="static"), name="static")


# ---------------------------------------------------------------------------
# Frontend
# ---------------------------------------------------------------------------


@app.get("/", include_in_schema=False)
async def serve_frontend() -> FileResponse:
    """Serve the single-page HTML frontend."""
    return FileResponse("static/index.html")
